version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: borough
      - name: neighborhood
      - name: taxi_trip
      - name: weather
      - name: payment_type
      - name: vendor_id
      - name: ratecode_id

  - name: ods
    schema: dwh_ods
    tables:
      - name: ods_borough
      - name: ods_neighborhood
      - name: ods_weather
      - name: ods_vendor
      - name: ods_taxi_trip
      - name: ods_payment_type
      - name: ods_ratecode