version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: borough
      - name: neighborhood
      - name: taxi_trip
      - name: weather
      - name: payment_type
      - name: vendor_id
      - name: ratecode_id