version: 2

models:
  - name: ods_borough
    columns:
      - name: id_borough
        tests:
          - not_null
          - unique

  - name: ods_neighborhood
    columns:
      - name: id_neighborhood
        tests:
          - not_null
          - unique

  - name: ods_taxi_trip
    columns:
      - name: id_taxi_trip
        tests:
          - not_null
          - unique

  - name: ods_weather
    columns:
      - name: id_weather
        tests:
          - not null
          - unique

  - name: ods_ratecode
    columns:
      - name: id_ratecode
        tests:
          - not null
          - unique

  - name: ods_payment_type
    columns:
      - name: id_payment_type
        tests:
          - not null
          - unique

  - name: ods_vendor
    columns:
      - name: id_vendor
        tests:
          - not null
          - unique

  - name: dm_zone

  - name: dm_data